apiVersion: apps/v1
kind: Deployment
metadata:
  name: od
  labels:
    app: od
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: od
  template:
    metadata:
      labels:
        app: od
        tier: od
    spec:
      containers:
      - name: od
        image: yangdori/od:latest
        imagePullPolicy: Always
        command: ['sh', '-c', 'echo 'od && sleep 6000']
        ports:
        - containerPort: 3000
          name: od
---
apiVersion: v1
kind: Service
metadata:
  name: od
  labels:
    app: od
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: od
    tier: od
  type: LoadBalancer
